### PR TITLE
Add mouse coordinates to os::Event::DropFiles event indicating the point where the drop of files took place on the target window

### PR DESCRIPTION
**Pull request by martincapello**
Implements pending work needed for https://github.com/aseprite/aseprite/issues/131

### CODE REVIEW

**Comment by dacap** [comment]
I've pushed other commit in the branch for the allevents example. I think we'll need a new kind of event, because DropFiles occurs when we release the mouse button, but for this we'll need some kind of feedback in the whole drag operation.

**Comment by martincapello** [comment]
Great. Yeah, we will need a new event for that. DragFiles?

**Comment by dacap** [comment]
That seems the best decision. I can merge this right now (as this PR adds the position of the DropFiles event correctly), and do the whole DnD work in a specific dnd branch for that. I could take some part of the implementation if you wish.

**Comment by martincapello** [comment]
Makes sense. Merge this as is and I will continue working in a different branch. First I would like to start drafting some implementation for macOS to agree with you about the api that should be exposed to laf clients and some implementation details.

**Pull request merged**
